config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'carrinho' => 'carrinho#index'
  get 'carrinho/limpar' => 'carrinho#limpar'
  get 'carrinho/:id' => 'carrinho#add'


  resources :bebidas
  root to: 'pagina#home'

  get 'pagina/home'

  get 'pagina/sobre'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bebida.rb
class Bebida < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/bebidas_controller.rb
class BebidasController < ApplicationController
  before_action :set_bebida, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]

  # GET /bebidas
  # GET /bebidas.json
  def index
    @bebidas = Bebida.all
  end

  # GET /bebidas/1
  # GET /bebidas/1.json
  def show
  end

  # GET /bebidas/new
  def new
    @bebida = Bebida.new
  end

  # GET /bebidas/1/edit
  def edit
  end

  # POST /bebidas
  # POST /bebidas.json
  def create
    @bebida = Bebida.new(bebida_params)

    respond_to do |format|
      if @bebida.save
        format.html { redirect_to @bebida, notice: 'Bebida was successfully created.' }
        format.json { render :show, status: :created, location: @bebida }
      else
        format.html { render :new }
        format.json { render json: @bebida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bebidas/1
  # PATCH/PUT /bebidas/1.json
  def update
    respond_to do |format|
      if @bebida.update(bebida_params)
        format.html { redirect_to @bebida, notice: 'Bebida was successfully updated.' }
        format.json { render :show, status: :ok, location: @bebida }
      else
        format.html { render :edit }
        format.json { render json: @bebida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bebidas/1
  # DELETE /bebidas/1.json
  def destroy
    @bebida.destroy
    respond_to do |format|
      format.html { redirect_to bebidas_url, notice: 'Bebida was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bebida
      @bebida = Bebida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bebida_params
      params.require(:bebida).permit(:nome, :preco, :litro, :categoria, :pais, :descricao, :avatar)
    end
end

app/controllers/carrinho_controller.rb
class CarrinhoController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def add
    id = params[:id]
      if session[:carrinho] then
        carrinho = session[:carrinho]
      else
          session[:carrinho] = {}
          carrinho = session[:carrinho]
      end

      if carrinho[id] then
        carrinho[id] = carrinho[id] + 1
      else
        carrinho[id] = 1
      end
    redirect_to :action => :index
  end

  def limpar
    session[:carrinho] = nil
    redirect_to :action => :index
  end

  def index
    if session[:carrinho] then
      @carrinho = session[:carrinho]
    else
      @carrinho = {}
    end
  end
end

app/controllers/pagina_controller.rb
class PaginaController < ApplicationController
  def home
  end

  def sobre
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bebidas_helper.rb
module BebidasHelper
end

app/helpers/carrinho_helper.rb
module CarrinhoHelper
end

app/helpers/pagina_helper.rb
module PaginaHelper
end

app/views/bebidas/_form.html.erb
<%= form_for @bebida, :html => { :class => "form-horizontal bebida" } do |f| %>

  <% if @bebida.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@bebida.errors.count, "error") %> prohibited this bebida from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @bebida.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :preco, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :preco, :class => 'form-control' %>
    </div>
    <%=f.error_span(:preco) %>
  </div>
  <div class="form-group">
    <%= f.label :litro, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :litro, :class => 'form-control' %>
    </div>
    <%=f.error_span(:litro) %>
  </div>
  <div class="form-group">
    <%= f.label :categoria, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= select("bebida", "categoria", ['Vodka', 'Whisky', 'Cerveja', 'Cachaça', 'Tequila', 'Licor', 'Vinho', 'Champagne'], {include_blank: true})%>
    </div>
    <%=f.error_span(:categoria) %>
  </div>
  <div class="form-group">
    <%= f.label :pais, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :pais, :class => 'form-control' %>
    </div>
    <%=f.error_span(:pais) %>
  </div>
  <div class="form-group">
    <%= f.label :descricao, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :descricao, :class => 'form-control' %>
    </div>
    <%=f.error_span(:descricao) %>
  </div>
    <div class="form-group">
    <%= f.label :Imagem, :class => 'control-label col-lg-2' %>
    <%= f.file_field :avatar %>
    </div>
    <%=f.error_span(:imagem) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bebidas_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/bebidas/edit.html.erb
<%- model_class = Bebida -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bebidas/index.html.erb
<%- model_class = Bebida -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name('Imagem') %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:preco) %></th>
      <th><%= model_class.human_attribute_name(:litro) %></th>
      <th><%= model_class.human_attribute_name(:categoria) %></th>
      <th><%= model_class.human_attribute_name(:pais) %></th>
      <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody> 
    <% @bebidas.each do |bebida| %>
      <tr>
        <td><%= image_tag bebida.avatar.url(:thumb) %></td>
        <td><%= bebida.nome %></td>
        <td><%= bebida.preco %></td>
        <td><%= bebida.litro %></td>
        <td><%= bebida.categoria %></td>
        <td><%= bebida.pais %></td>
        <td><%= bebida.descricao %></td>
        <td>
          <% if admin_signed_in? == true && user_signed_in? == false %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_bebida_path(bebida), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        bebida_path(bebida),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          <% end %>
          <td><a href="/carrinho/<%= bebida.id %>"> Adicionar ao carrinho</a></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if admin_signed_in? == true && user_signed_in? == false %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_bebida_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/bebidas/new.html.erb
<%- model_class = Bebida -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bebidas/show.html.erb
<%- model_class = Bebida -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @bebida.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:preco) %>:</strong></dt>
  <dd><%= @bebida.preco %></dd>
  <dt><strong><%= model_class.human_attribute_name(:litro) %>:</strong></dt>
  <dd><%= @bebida.litro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:categoria) %>:</strong></dt>
  <dd><%= @bebida.categoria %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pais) %>:</strong></dt>
  <dd><%= @bebida.pais %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
  <dd><%= @bebida.descricao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_name) %>:</strong></dt>
  <dd><%= @bebida.avatar_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_content_type) %>:</strong></dt>
  <dd><%= @bebida.avatar_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_size) %>:</strong></dt>
  <dd><%= @bebida.avatar_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_updated_at) %>:</strong></dt>
  <dd><%= @bebida.avatar_updated_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              bebidas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bebida_path(@bebida), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bebida_path(@bebida),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/carrinho/index.html.erb
<h1>Carrinho de Compras</h1>

<br>
<% total = 0 %>

<ul>
<% @carrinho.each do |id, quantity| %>
    <% bebida = Bebida.find_by_id(id) %>

    <li>
      <%= link_to bebida.nome, bebida %>
      <td><%= image_tag bebida.avatar.url(:thumb) %></td>
      <p>Descrição: <%= bebida.descricao %><p>
      <p><%= number_to_currency(bebida.preco, :unit => '$') %></p>
      <p>Quantidade: <%= quantity %></p>
    </li>
    <hr>
    <% total += quantity * bebida.preco %>
<% end %>

<p><b>TOTAL: <%= number_to_currency(total, :unit => '$') %></b></p>
</ul>
<% if total > 0 %>
  <li><%= link_to 'Comprar (Paypal)','https://www.paypal.com/br/home',{:target =>
  "_new"} %></li>
  <br>
  <li><%= link_to 'Esvaziar o Carrinho', carrinho_limpar_path %></li>
<% else %>
  <p> Carrinho Vazio no momento. Comece a comprar suas bebidas </p>
<% end %>
<br>
<li><%= link_to 'Comprar Mais', bebidas_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    
  <head>
    <title>Distribuidora de Bebidas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li>
                        <a href="/bebidas">Shop</a>
                    </li>
                    <li>
                        <a href="/carrinho">Carrinho</a>
                    </li>
                    <li>
                        <a href="/pagina/sobre">Sobre</a>
                    </li>
                    <li>
                    <% if user_signed_in? %>
                    
                        <%= link_to "Sair", destroy_user_session_path, method: :delete %>
                    
                    <% else %>
                    <%= link_to "Cadastrar", new_user_registration_path %>
                    </li>
                    <li>
                    <%= link_to "Login", user_session_path %>
                    <% end %>
                    </li>
                    
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pagina/home.html.erb
<!DOCTYPE html>
<html class="full" lang="en">
<!-- Make sure the <html> tag is set to the .full CSS class. Change the background image in the full.css file. -->

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Full - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/full.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <!-- Put your page content here! -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/pagina/sobre.html.erb
<h1>Sobre nós.</h1>
<p>Daniel Marques Rangel - 15/0008228</p>
<p>Filipe Miranda de Macedo - 15/0125518</p>
<p>Tema: Site de bebidas online desenvolvido com Ruby on Rails utilizando principalmente as gems: devise e twitter-bootstrap.
<p></p>
<p>Espaço destinado à login do administrador.</p>


<p><% if admin_signed_in? %>
<%= link_to "Sair", destroy_admin_session_path, method: :delete %>
<% else %>
<%= link_to "Login", admin_session_path %>            
<% end %>
</p>                    